name: github pages

on:
  push:
    branches:
      - source

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peteroneilljr/peteroneilljr@v2
        with:
          hugo-version: '0.72.0'

      - name: Build
        run: hugo

      - name: Deploy
        uses: peteroneilljr/peteroneilljr@v3
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          publish_dir: ./docs
          publish_branch: master  # deploying branch